"""added last_used_at to authenticators

Revision ID: e96194e7b64d
Revises: 9fecbb2fefb6
Create Date: 2025-01-16 15:55:36.248211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96194e7b64d'
down_revision: Union[str, None] = '9fecbb2fefb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authenticators_credential_id', table_name='authenticators')
    op.drop_index('ix_authenticators_id', table_name='authenticators')
    op.drop_table('authenticators')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('authenticators',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('credential_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('public_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sign_count', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authenticators_id', 'authenticators', ['id'], unique=False)
    op.create_index('ix_authenticators_credential_id', 'authenticators', ['credential_id'], unique=1)
    # ### end Alembic commands ###
